FROM python:3.5

ENV PYTHONUNBUFFERED 1

RUN pip install -U pip

RUN mkdir -p /code/
WORKDIR /code

ADD project/requirements.txt requirements.txt
RUN pip install -r requirements.txt --no-cache-dir

ENV DOCKER 1

EXPOSE 8000
